title: Rustlings Quarry
description: A place for rust resources, tips, and tricks
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
github:
  zip_url:
  owner_url: https://github.com/IsaacAlao 
  owner_name: IsaacAlao
  repository_url: https://github.com/IsaacAlao/rustlings-quarry 
  another_url: another value
