title: Rustlings Quarry
description: A place for rust resources, tips, and tricks
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
github:
  zip_url:
  owner_url: https://github.com/IsaacAlao 
  owner_name: IsaacAlao
  repository_url: https://github.com/IsaacAlao/rustlings-quarry 
  another_url: another value
